theme: jekyll-theme-midnight
title: Níck
description: theoretical physicist
github:
  is_project_page: false

summarize_publications: true # link to publication summaries

collections:
  publications:
    output: true
  teaching:
    output: false
  interests:
    output: true
  seminars:
    output: false
  quotes: 
    output: false
    
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
      remark: "This is a simplified version of the work linked above, written to be an extended abstract or less formal account of the results. For further details, please check the official publication. This account is written independently by Níck Aguiar Alves only and may not fully reflect the points of view of other coauthors."
      summarized: true
  - scope:
      path: ""
      type: "interests"
    values:
      layout: "interest"
